using NUnit.Framework;
using Ploeh.AutoFixture;
using ForgetTheMilk;

namespace ForgetTheMilkTests
{
    /*AutoFixture can be used to generate test data when the data doesn't really 
     *matter, eg, string 'hello'; we call such date 'anonymous'
     */
    class AutoFixtureAnonymousDataExample
    {
        [Test]
        public void TestWithAutogeneratedString()
        {
            var fixture = new Fixture();

            //Using fixture to create 'anonymous' data
            var inputString = fixture.Create<string>();
            var sut = new StringUtils();
            var result = sut.MakeUpper(inputString);

            Assert.AreEqual(inputString.ToUpper(), result);
        }

        [Test]
        public void CTestWithAutogeneratedSeededString()
        {
            var fixture = new Fixture();

            // To have the input string prefixed with 'sarah'
            var inputString = fixture.Create<string>("sarah");
            var sut = new StringUtils();
            var result = sut.MakeUpper(inputString);

            Assert.AreEqual(inputString.ToUpper(), result);
        }

        [Test]
        public void TestWithAUtoGeneratedNumberAndString()
        {
            var fixture = new Fixture();
   
            var inputString = fixture.Create<string>();
            var inputNum = fixture.Create<int>();

            var sut = new StringUtils();
            var result = sut.AppendNumberToString(inputString, inputNum);

            Assert.AreEqual(inputString + inputNum, result);
        }
    }
}
